version: '3.3'
services:

  db:
    container_name: "wc_db"
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 3

  app:
    container_name: "wc_app"
    build: .
    sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
    command: sh -c "cd app/db && alembic upgrade head && cd ../.. && python app/main.py --start program"
    depends_on:
      db:
        condition: service_healthy
